[WIP] Timer Service
sdslabs/Athena pull request #29
Opened 2023-08-31 08:52 UTC by Demigod345

2023-09-01 15:14 UTC, jainl28patel reviewed
Solve all the above mentioned changes.

2023-09-01 15:14 UTC, jainl28patel commented on src/services/timer.ts
> +    if (reason === 'server namespace disconnect') {
rather than using strings use `enums`

2023-09-01 15:43 UTC, jainl28patel commented on src/types/quiz.ts
> +
move in `IParticipant.time`

2023-09-01 15:43 UTC, jainl28patel commented on src/services/timer.ts
> +  }
Move whole thing to the db, can't store at runtime in the variables.

2023-09-01 20:40 UTC, jainl28patel requested changes

2023-09-01 20:40 UTC, jainl28patel commented on src/server.ts
> +    else if (res.statusCode === 400) {
correct this

2023-09-01 20:40 UTC, jainl28patel commented on src/services/timer.ts
> +      user.time.endQuiz = new Date('2023-09-02').getTime()
Remove hardcoded value

2023-09-02 09:55 UTC, jainl28patel requested changes

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +    logger.silly("Quiz doesn't exist with QuizId: ", quizId)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +    logger.silly('Quiz is not Published or is not Accepting Answers with QuizId: ', quizId)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +    logger.silly("User doesn't exist with userId: ", userId)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +    logger.silly(reason)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +    logger.error(`Error updating quiz with quizId: ${quiz._id} : `, error)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +      logger.silly('⚡️[server]: UserId or QuizId is empty.')
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +      logger.silly('Wrong quizId or userId')
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +      logger.silly(`Server-Side Disconnection`)
Remove

2023-09-02 09:55 UTC, jainl28patel commented on src/services/timer.ts
> +      logger.silly(`Quiz was never Joined`)
Remove

2023-09-02 13:23 UTC, jainl28patel reviewed
rename timer.js to timer.ts no need to remove use js file

2023-09-02 13:34 UTC, jainl28patel requested changes

2023-09-02 13:34 UTC, jainl28patel commented on src/services/timer.ts
> +  }
`reason` is redundant. remove it

2023-09-02 13:34 UTC, jainl28patel commented on src/services/timer.ts
> +  if (!isAcceptingAnswers || !isGivingQuiz) {
```suggestion
  if (!isAcceptingAnswers || isGivingQuiz) {
```
change this. if user is giving quiz then we should return false

2023-09-02 13:34 UTC, jainl28patel commented on src/services/timer.ts
> +    console.log(data)
```suggestion
```

2023-09-02 13:34 UTC, jainl28patel commented on src/services/timer.ts
> +    console.log(socket.quizId)
```suggestion
```

2023-09-02 13:34 UTC, jainl28patel commented on src/services/timer.ts
> +      }
```suggestion
```

2023-09-02 13:46 UTC, Demigod345 commented on src/services/timer.ts
> +      }
What is the desired change here?

2023-09-02 13:51 UTC, jainl28patel commented on src/services/timer.ts
> +      }
Why do we handle the case where `user.time.left<0` ?
It will be stored in db and next time user can't open quiz as per your `join_quiz` logic.
Also as I told earlier we don't have to handle submit in this part. we have different API for that

2023-09-02 13:52 UTC, jainl28patel commented on src/services/timer.ts
> +      }
inshort remove this part :)

2023-09-02 13:54 UTC, Demigod345 commented on src/services/timer.ts
> +      }
Okay done hai ji

2023-09-02 14:03 UTC, jainl28patel approved these changes

2023-09-02 14:04 UTC, merged